interface IItem {
  name?: string;
  title?: string;
  gender?: string;
  height?: string;
  mass?: string;
  planets?: string | string[];
  starships?: string | string[];
  species?: string | string[];
  vehicles?: string | string[];
  model?: string;
  length?: string;
  homeworld?: string;
  hair_color?: string;
  eye_color?: string;
  skin_color?: string;
  films?: string | string[];
  birth_year?: string;
  characters?: string[];
  episode_id?: number;
  director?: string;
  producer?: string;
  starship_class?: string;
  manufacturer?: string;
  crew?: string;
  passengers?: string;
  pilots?: string[];
  vehicle_class?: string;
  classification?: string;
  designation?: string;
  average_height?: string;
  average_lifespan?: string;
  eye_colors?: string;
  hair_colors?: string;
  skin_colors?: string;
  language?: string;
  url?: string;
  diameter?: string;
  rotation_period?: string;
  orbital_period?: string;
  gravity?: string;
  population?: string;
  climate?: string;
  terrain?: string;
  residents?: string[];
  surface_water?: string;
}

export default IItem;
